### ISSUE TITLE
Can't run 'Face Recognition'script

### ISSUE THREAD

**Issue by DeoBye** [ZPGuiGroupWhu/ClusteringDirectionCentrality#8]
Hey, Thanks for your contribution to such a nice work.

I try to run the code 'main.m' in Face Recognition but I can't make it run due to the error in line 41.
It seems the error is about funciton pca, it's said the number of parameters is wrong.

How to deal with this?

**Comment by pdh-coder** [comment]
Thank for using our code. I have uploaded a 'pca.m' file in the 'Face Recognition', please find and check. Hope this helps.

**Comment by DeoBye** [comment]
Thanks, it works now.
